apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  namespace: beehive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: monitor
          image: beehive-im-runtime:latest
          imagePullPolicy: IfNotPresent
          command:
            - /opt/beehive/run-service.sh
            - monitor
            - /opt/beehive/conf/runtime/monitor.xml
          volumeMounts:
            - name: conf
              mountPath: /opt/beehive/conf/runtime
      volumes:
        - name: conf
          configMap:
            name: beehive-conf
