apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: beehive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "111111"
            - name: MYSQL_DATABASE
              value: testdb
          ports:
            - containerPort: 3306
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p111111"]
            initialDelaySeconds: 20
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: beehive
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
